# Generated by Django 5.1.6 on 2025-02-18 20:13

import kutuphane.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktracking',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penalty',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 haneli ISBN numarası', max_length=13, unique=True, validators=[kutuphane.models.isbn_validator]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
