# Generated by Django 5.1.6 on 2025-02-19 19:37

import kutuphane.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0002_booktracking_notified_at_penalty_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=kutuphane.models.default_due_date),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expiration_date',
            field=models.DateTimeField(default=kutuphane.models.default_expiration_date),
        ),
    ]
